spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5430/countries
    username: root
    password: password
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        show_sql: true
        hbm2ddl:
          auto: update
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
